services:
  cassandra:
    image: cassandra:latest
    container_name: cassandradb
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_START_RPC=true
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 10s
      retries: 10

  seeder:
    image: bash
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./create-demo-db.sql:/docker-entrypoint-initdb.d/create-demo-db.sql
      - ./seeder.sh:/seeder.sh
    entrypoint: ["bash", "/seeder.sh"]

volumes:
  cassandra_data:
